### ISSUE TITLE
Login error: ORA-499

### ISSUE THREAD

**Issue by crescentjanus** [fxcm/ForexConnectAPI#11]
Hi,

I got this error message when I run the GetLivePrices sample project.

"Login error: ORA-499: Unable to obtain station descriptor. HTTP request failed object='/Hosts.jsp?ID=381250&PN=Demo&SN=ForexConnect&MV=5&LN=701050936&AT=PLAIN' errorCode=56"

And I am in China Mainland, not using any vpn.  I don't know how to fix this.

Thanks.

**Comment by crescentjanus** [comment]
By the way, the TSII runs well. Just the sample project fails to connect.

**Comment by FXCMAPI** [comment]
we did a hot fix, you should be good
