### ISSUE TITLE
got the same error again

### ISSUE THREAD

**Issue by crescentjanus** [fxcm/ForexConnectAPI#12]
"Login error: ORA-499: Unable to obtain station descriptor. HTTP request failed object='/Hosts.jsp?ID=285031859&PN=Demo&SN=ForexConnect&MV=5&LN=701050936&AT=PLAIN' errorCode=52"

Run the getoffer sample project, then got this error message, need help.

Thanks.

**Comment by fxcm-dhalpert** [comment]
please update Forex Connect API with the latest version 1.6.4
http://fxcodebase.com/bin/forexconnect/1.6.4/ForexConnectAPI-1.6.4-win32.exe
http://fxcodebase.com/bin/forexconnect/1.6.4/ForexConnectAPI-1.6.4-win64.exe

for Python please update to 1.6.43 version:
https://pypi.org/project/forexconnect/1.6.43/

**Comment by crescentjanus** [comment]
Problem solved ^_^
sorry to bother you.
Thank you very much.
Wondering can  you give me the FIX api credentials ?  
Here is my login, D103435662
Thank you!

**Comment by fxcm-dhalpert** [comment]
Please check the URL it should be   www.fxcorporate.com/Hosts.jsp  (for all account types),
the connection should be "Demo" or "Real" for demo or real account.

**Comment by meb21uk** [comment]
Hi,

Thank you for your reply. I think the error was in someway related to being on an older OS version(Big Sur). Having swapped to Ubuntu and replaced Live for Demo as you highlighted; the error has resolved itself. 

No further support required.

Thanks
