### ISSUE TITLE
pip install not available?

### ISSUE THREAD

**Issue by sam30606** [fxcm/ForexConnectAPI#13]
![image](https://user-images.githubusercontent.com/61706675/205653570-63b70927-ef99-4824-96a0-9ab6be9a65ce.png)

**Comment by FXCMAPI** [comment]
Hi,

ForexConnect currently works only with Python versions 3.5, 3.6 and 3.7

**Comment by sam30606** [comment]
Got it, Thanks!

I uesd fxcmpy before, but the connection is very unstable.
