### ISSUE TITLE
ForexConnect API

### ISSUE THREAD

**Issue by monsterlady** [fxcm/ForexConnectAPI#15]
```
from forexconnect import fxcorepy
```
can not import fxcorepy.... It said that  **Cannot find reference 'fxcorepy' in __init__.py**. 
And in the python sample, I can not find the example of creating market order with TP/SL

**Comment by fxcm-dhalpert** [comment]
Please check if Forex Connect is installed:  pip install forexconnect
Works only with Python versions 3.5, 3.6 and 3.7

Example programs in Python for Forex Connect API:  https://github.com/gehtsoft/forex-connect/tree/master/samples/Python
https://fxcodebase.com/bin/forexconnect/1.6.5/help/Python/web-content.html#index.html
