### ISSUE TITLE
Login access denied

### ISSUE THREAD

**Issue by jjqqkk** [fxcm/ForexConnectAPI#20]
I got the following error on login: 

```
SessionStatus onLoginFailed: 19915;DAS 19915: ZDas Exception
ORA-20003:
ORA-20003: Access denied
ORA-06512: at "U10R26.API", line 760
ORA-06512: at "U10R26.API", line 789
ORA-06512: at line 1
```

Username/password is correct. Please look into the problem, thanks.

**Comment by FXCMAPI** [comment]
we disable ForexConnect API access on MT4 accounts, it is a business decision. 
you can still use your account on MT4 platform.

**Comment by jjqqkk** [comment]
Thank you for the information... but I have never accessed MT4 since day 1, always on TS/TSWeb and ForexConnect, could you please tell me how to switch my account type back to TS?

**Comment by FXCMAPI** [comment]
please talk to our sales team, sales@fxcm.com

**Comment by jjqqkk** [comment]
> please talk to our sales team, [sales@fxcm.com](mailto:sales@fxcm.com)

Thank you so much!

**Comment by jjqqkk** [comment]
Hi, I've created a new TS2 account, unfortunately FC API raises the same exception. 

<img width="818" alt="Screenshot 2023-09-27 at 4 13 22 PM" src="https://github.com/fxcm/ForexConnectAPI/assets/45589513/873efa90-4dc4-45fd-beb0-8eeff34be97f">

```
SessionStatus onLoginFailed: 19915;DAS 19915: ZDas Exception
  ORA-20003:
ORA-20003: Access denied
ORA-06512: at "U10R15.ERROR_EX", line 99
ORA-06512: at "U10R15.ERROR_EX", line 114
ORA-06512: at "U10R15.API_EX", line 1950
ORA-06512: at line 1
```

BTW, this new account starts with "400".

My bot works well with another "800" account. I am testing on the same computer, so there might be some more issue on the server side?

**Comment by fxcm-dhalpert** [comment]
Please email the connection parameters to api@fxcm.com
