### ISSUE TITLE
Login Fail.  Server issues?

### ISSUE THREAD

**Issue by jimmylai-hk** [fxcm/ForexConnectAPI#21]
I'm able to login FXCM trade station with the ACCOUNT_ID and password.

However, I cannot login using the code below using the same ACCOUNT_ID and password.

The same code can be run yesterday without any problem.  What's the issue?

def session_status_changed(session: fxcorepy.O2GSession,
                           status: fxcorepy.AO2GSessionStatus.O2GSessionStatus):
    print("Trading session status: " + str(status))   

def init_forexconnect(fx, ACCOUNT_ID, PASSWORD):
    fx.login(ACCOUNT_ID, PASSWORD, "fxcorporate.com/Hosts.jsp",
             "DEMO", session_status_callback=session_status_changed)

with ForexConnect() as fx:
     init_forexconnect(fx, ACCOUNT_ID,PASSWORD)
     print(f"Success")

**Comment by fxcm-dhalpert** [comment]
To login please use the username no account ID.

**Comment by Maxim-Fil** [comment]
I have the same problem - module write "User or connection doesn't exist"
