### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by jjqqkk** [fxcm/ForexConnectAPI#23]
Hi, I went into trouble logging into the system via API starting from this week's trading session.

1. Around 23:00 (UTC) Nov-26, the bot raised incorrect username/password error, though i didn't change anything on my side.
2. After an hour around 00:00 (UTC) Nov-27 , the bot raised login timeout. I tried to login the web TS manually, failed, and then I logged in myfxcm.com with the username/password successfully. So the account is correct.
3. Then I contacted the support team about the issue. 
4. Now at the time of writing, the bot raises this error: `SessionStatus onLoginFailed: HTTP request failed object='/pdas/servlet?rnd=1701069874453' errorCode=503`. At the same time, I can still login myfxcm. 

Please help, thank you.

**Comment by fxcm-dhalpert** [comment]
Please try to connect now, if the issue persist please email the username to api@fxcm.com.

**Comment by jjqqkk** [comment]
Working now, thank you so much, great service!

**Comment by jjqqkk** [comment]
Hi, again, my 400 account login timeout, both on the web TS and the API. 800 account works fine. Could you help?

**Comment by jjqqkk** [comment]
> may i know your 400 account number?

Hi, login works fine after a few hours, both on TS and API, thank you.
