### ISSUE TITLE
History prices stop working

### ISSUE THREAD

**Issue by nirp0109** [fxcm/ForexConnectAPI#25]
My wife close my computer while it run my python program, after start again I can not get history.
Success get  login, report of account, current offers, but not history.
Also the example of getting history fail.

Got this exception:
Exception: QuotesManager error: HTTP request failed object='/pricearchive/catalog.xml' errorCode=28 code: QuotesServerConnectionError subcode: 28

I am using windows 11 (also didn't work on windows 10 before upgrade os)
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by fxcm-dhalpert** [comment]
I tested sample code GetHistPrices.py and it works ok, try with a different demo account or different PC.
https://github.com/gehtsoft/forex-connect/blob/master/samples/Python/GetHistPrices.py

**Comment by nirp0109** [comment]
Hi Daniel,

My old laptop works fine. Still need to find the issue on my good and fast
computer.

Thanks,
Nir Parickman
