### ISSUE TITLE
Forex Connect new python version support

### ISSUE THREAD

**Issue by nirp0109** [fxcm/ForexConnectAPI#26]
Now python 3.7 is not supported anymore is there a plan to support higher python versions?

Thanks
regards
Nir

**Comment by jabernalv** [comment]
Support for Higher Python Versions

Dear Forex Connect Team,

I hope this message finds you well. I wanted to inquire about the plans regarding the support for higher Python versions in MetaTrader. As Python 3.7 is no longer supported, many users are looking forward to compatibility with newer Python releases.

Is there a roadmap or any updates regarding this matter? Your insights would be greatly appreciated.

Thank you for your attention to this request.

Best regards,
Jairo Bernal

**Comment by fxcm-dhalpert** [comment]
Unfortunately currently we don't have plan to update the Python wrapper.

**Comment by nirp0109** [comment]
The newer version of python for support I refer to forexconnect api in
python, not metaTrader.

Regards
Nir Parickman

**Comment by nf78** [comment]
Can I help with updating the Python wrapper for newer versions of Python?

**Comment by FXCMAPI** [comment]
Unfortunately we don't have plan to update the Python wrapper.

**Comment by nf78** [comment]
Hi, thanks for your reply, now I'm very interested in knowing the reason(s) why there aren't plans to update such an important wrapper? I just would like to understand better because I see a lot of interest in this. Also because I'm currently developing my own trading app with this wrapper and would like to know the impact on it. Are there plans to migrate to a different protocol, or simply any other technical restrictions? Thanks in advance

**Comment by FXCMAPI** [comment]
we decided to move to our new FCLite API
https://docs.gehtsoftusa.com/fclite_new/#main.html

**Comment by nf78** [comment]
Thanks for letting me know, and just to be on the safe side, in that case, is ForexConnect API (python) still going to continue active for a long period of time, or should I start considering using FCLite API instead on another language?

**Comment by FXCMAPI** [comment]
we will not take the python package off, but will not upgrade it. 
I suggest you try our new FCLite API.

**Comment by nf78** [comment]
ok thanks for letting me know

**Comment by Pedanfer** [comment]
> we will not take the python package off, but will not upgrade it. I suggest you try our new FCLite API.

But the FC Lite API isn't listed in the FXCM page still (the ForexConnect API is) and the changelog of the project shows no updates since 2024. Doesn't give a whole lot of confidence.
