### ISSUE TITLE
How to change trade Stop Limit via vba / excel?

### ISSUE THREAD

**Issue by AVISHAY123** [fxcm/ForexConnectAPI#7]
How to change trade Stop Limit via vba / excel?
thank you

**Comment by AVISHAY123** [comment]
Thank you it works
Which command can I add to configure trailstep?

**Comment by AVISHAY123** [comment]
I get error "object required"
there is no valuemapChangeOrder object

**Comment by AVISHAY123** [comment]
There is no error now, but it does nothing

**Comment by fxcm-dhalpert** [comment]
when you create the new order add the trailing stop with the attached stop, using same
Call valuemapChangeOrder.setInt(RequestParamsEnum_TrailStep, 15)
just add it to the CreateOrder command.

**Comment by fxcm-dhalpert** [comment]
what are the valuemap fields

**Comment by AVISHAY123** [comment]
Set valueMap = requestFactory.createValueMap()
    Call valueMap.setString(RequestParamsEnum_Command, constants.Commands.createOrder)
    Call valueMap.setString(RequestParamsEnum_OrderType, constants.orders.TrueMarketOpen)
    Call valueMap.setInt(RequestParamsEnum_Amount, amount)
    Call valueMap.setString(RequestParamsEnum_BuySell, buysell) 
    Call valueMap.setString(RequestParamsEnum_AccountID, MyAcc)
    Call valueMap.setString(RequestParamsEnum_OfferID, offer.OfferID)
    Call valueMap.setDouble(RequestParamsEnum_RateLimit, Up) 
    Call valueMap.setDouble(RequestParamsEnum_RateStop, Dn) 
    Call valueMap.setInt(RequestParamsEnum_TrailStep, 50)

**Comment by fxcm-dhalpert** [comment]
Please replace TrailStep with TrailStepStop
so the trailing stop will be for the attached stop not for the main order

**Comment by AVISHAY123** [comment]
Now, the order not created

**Comment by fxcm-dhalpert** [comment]
Example ELS order with Trailing Stop 

O2GRequest request = null;
O2GRequestFactory requestFactory = session.getRequestFactory();

O2GValueMap valuemap = requestFactory.createValueMap();
valuemap.setString(O2GRequestParamsEnum.Command, Constants.Commands.CreateOrder);
valuemap.setString(O2GRequestParamsEnum.OrderType, "OM"); valuemap.setString(O2GRequestParamsEnum.AccountID, sAccountID);
valuemap.setString(O2GRequestParamsEnum.OfferID, sOfferID);
valuemap.setString(O2GRequestParamsEnum.BuySell, sBuySell);
valuemap.setInt(O2GRequestParamsEnum.Amount, iAmount);
valuemap.setDouble(O2GRequestParamsEnum.Rate, dRate);
valuemap.setDouble(O2GRequestParamsEnum.RateLimit, dRateLimit);
valuemap.setDouble(O2GRequestParamsEnum.RateStop, dRateStop);
valuemap.setString(O2GRequestParamsEnum.CustomID, "EntryOrderWithStopLimit");
valuemap.setString(O2GRequestParamsEnum.TimeInForce, Constants.TIF.GTC);
valuemap.setInt(O2GRequestParamsEnum.TrailStepStop, dTrailStepStop); <---- Trailing Stop

**Comment by AVISHAY123** [comment]
Thank you
but trade not created
If I omit the last line, it created

**Comment by fxcm-dhalpert** [comment]
which version of FC API you using?

**Comment by AVISHAY123** [comment]
1.4.1

**Comment by fxcm-dhalpert** [comment]
the fixed trailing stop should be 10 or above, dynamic trailing stop should be 1, just tested and it seems ok

Call valueMap.setInt(RequestParamsEnum_TrailStepStop, 10)

**Comment by AVISHAY123** [comment]
still not created with that line

**Comment by fxcm-dhalpert** [comment]
can you please email the related snip code and parameters values  to api@fxcm.com

**Comment by AVISHAY123** [comment]
I just did
