### ISSUE TITLE
link accounts in  vba \ excel

### ISSUE THREAD

**Issue by AVISHAY123** [fxcm/ForexConnectAPI#8]
I noticed that there is an option to link accounts in a way that allows one account to send commands to another account.
It happens to me between some of my accounts.
How am I actually supposed to do that link?
And, how to get information about orders and trades from another account?

**Comment by fxcm-dhalpert** [comment]
one username/login may have multiple trading accounts, with real login you can add account from myfxcm.com, for demo login please email your login to api@fxcm.com.
when placing order one of the parameters is the account_id, each trading account has unique account_id and account number.
